### PR TITLE
Add CI to allow instrumentation tests

### PR DESCRIPTION
**Pull request by helios175**

### CODE REVIEW

**Review by zach-klippenstein — APPROVED** [review]

**Comment by zach-klippenstein** [comment]
Wow, the Mac workers are really not happy today.

**Comment by helios175** [comment]
Add instrumentation tests.

**Comment by helios175** [comment]
Add instrumentation tests.

**Comment by helios175** [comment]
It was not merged! Reopening for merge.

**Comment by helios175** [comment]
It only tests on API 21+ because it seems there's emulator (or it doesn't work for infra reasons).
That probably means we shouldn't support pre 21 versions.

**Review by zach-klippenstein — APPROVED** [review]

**Comment by zach-klippenstein** [comment]
This PR title is misleading, it doesn't actually add any tests, it just configures CI to run them (and there aren't any, right?)

**Pull request merged**
